[package]
name = "kuvakannu"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.7.0"
actix-web = "4.15.0"
anyhow = "1.0.104"
async-fs = "2.2.0"
colog = "1.4.0"
futures-lite = "2.6.1"
log = "0.4.34"
markdown = "1.0.0"
sailfish = "0.11.4"
tokio = "1.53.1"

[dev-dependencies]
reqwest = { version = "0.13.4", features = ["blocking"] }
