[package]
name = "kuvakannu"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.7.0"
actix-web = "4.15.0"
async-fs = "2.2.0"
futures-lite = "2.6.1"
markdown = "1.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = "1.53.1"

[dev-dependencies]
reqwest = { version = "0.13.4", features = ["blocking"] }
